feat: skip documentation building when there are no change

diff --git a/.readthedocs.yml b/.readthedocs.yml
--- a/.readthedocs.yml
+++ b/.readthedocs.yml
@@ -9,8 +9,20 @@ build:
   tools:
     python: "3.12"
 
+  jobs:
+    post_checkout:
+      # Cancel building pull requests when there aren't changed in the docs directory or YAML file.
+      # If there are no changes (git diff exits with 0) we force the command to return with 183.
+      # This is a special exit code on Read the Docs that will cancel the build immediately.
+      - |
+        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml;
+        then
+          exit 183;
+        fi
+
 mkdocs:
   configuration: docs/mkdocs.yml
+
 python:
   install:
     - requirements: docs/requirements.txt
